{% set version = "2.0" %}

package:
  name: bmipy
  version: {{ version }}

source:
  url: https://github.com/csdms/bmi-python/archive/v{{ version }}.tar.gz
  sha256: 8f9698cee8832715d8b6826b6a1c9610990ae05a175dafcadafa6c2a58907c21

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - bmipy-render = bmipy.cmd:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - black  # [py3k]
    - click
    - jinja2
    - numpy
    - six
    - typing  # [py2k]

test:
  imports:
    - bmipy
  commands:
    - bmipy-render --help
    - bmipy-render --version
    - bmipy-render MyBmi


about:
  home: http://github.com/csdms/bmipy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python bindings for the Basic Model Interface'
  description: |
    An abstract base class for implementing a Basic Model Interface in Python.
    Also included are some useful utilities for implementers.
  doc_url: http://bmipy.readthedocs.io/
  dev_url: https://github.com/csdms/bmi-python

extra:
  recipe-maintainers:
    - mcflugen
